on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository name"
        required: true
        type: string
      ref:
        description: "ref to check out"
        required: true
        type: string

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "arbisee/${{ inputs.repository }}"
          ref: "${{ inputs.ref }}"
          token: "${{ secrets.REPO_TOKEN }}"
      - run: ls
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Freeze dependencies
        run: pip freeze > requirements.txt
      - name: Install pip-licenses
        run: pip3 install pip-licenses
      - name: Scan for licenses
        run: pip-licenses --fail-on="GPL License"
        working-directory: .
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
          path: "."
