on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository name"
        required: true
        type: string
      ref:
        description: "ref to check out"
        required: true
        type: string

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "arbisee/${{ inputs.repository }}"
          ref: "${{ inputs.ref }}"
          token: "${{ secrets.REPO_TOKEN }}"
      - run: ls
